### ISSUE TITLE
scanstatus 가 false로 와서 목록 출력되지 않는 현상

### ISSUE THREAD

**Issue by gyunwoo0** [NORMA-Inc/AtEar#8]
run.py 있는 경로로 이동하지 않고, python Atear/Atear/run.py 이런식으로 경로를 지정할 경우, main_app의 scanstatus가 false를 반환함
쿼리 문제로 보임..

**Comment by NORMA-Inc** [comment]
해당 경로로 가서 실행 바랍니다.
